export const GET_ALUBMS_START = 'GET_ALBUMS_START';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const FILTER_ALBUM_SUCCESS = "FILTER_ALBUM_SUCCESS";
export const GET_OLD_STATE_SUCCESS = "GET_OLD_STATE_SUCCESS";


